services:
  db:
    container_name: "mysql_marketplace"
    image: mysql:8.0.33
    networks:
      - default
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./.docker/db.sql:/docker-entrypoint-initdb.d/0_init.sql
      - .docker/mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "--password=${MYSQL_ROOT_PASSWORD}" ]
      timeout: 20s
      retries: 10

  app:
    container_name: "go_marketplace"
    build:
      context: .
      dockerfile: .docker/go/Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src:/app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "pma_marketplace"
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - db
    networks:
      - default

networks:
  default:

volumes:
  mysql_amar_data:
